import { CurrencyCodeType } from '../types';

export const CurrencyCode: CurrencyCodeType[] = [
  { key: 'usd', value: 'USD', name: 'United States Dollar' },
  { key: 'eur', value: 'EUR', name: 'Euro' },
  { key: 'gbp', value: 'GBP', name: 'British Pound Sterling' },
  { key: 'cad', value: 'CAD', name: 'Canadian Dollar' },
  { key: 'aud', value: 'AUD', name: 'Australian Dollar' },
  { key: 'jpy', value: 'JPY', name: 'Japanese Yen' },
  { key: 'inr', value: 'INR', name: 'Indian Rupee' },
  { key: 'nzd', value: 'NZD', name: 'New Zealand Dollar' },
  { key: 'chf', value: 'CHF', name: 'Swiss Franc' },
  { key: 'zar', value: 'ZAR', name: 'South African Rand' },
  { key: 'aed', value: 'AED', name: 'United Arab Emirates Dirham' },
  { key: 'all', value: 'ALL', name: 'Albanian Lek' },
  { key: 'amd', value: 'AMD', name: 'Armenian Dram' },
  { key: 'ang', value: 'ANG', name: 'Netherlands Antillean Guilder' },
  { key: 'aoa', value: 'AOA', name: 'Angolan Kwanza' },
  { key: 'ars', value: 'ARS', name: 'Argentine Peso' },
  { key: 'awg', value: 'AWG', name: 'Aruban Florin' },
  { key: 'bbd', value: 'BBD', name: 'Barbadian Dollar' },
  { key: 'bgn', value: 'BGN', name: 'Bulgarian Lev' },
  { key: 'bhd', value: 'BHD', name: 'Bahraini Dinar' },
  { key: 'bmd', value: 'BMD', name: 'Bermudan Dollar' },
  { key: 'brl', value: 'BRL', name: 'Brazilian Real' },
  { key: 'btc', value: 'BTC', name: 'Bitcoin' },
  { key: 'clp', value: 'CLP', name: 'Chilean Peso' },
  { key: 'cnh', value: 'CNH', name: 'Chinese Yuan (Offshore)' },
  { key: 'cny', value: 'CNY', name: 'Chinese Yuan' },
  { key: 'czk', value: 'CZK', name: 'Czech Republic Koruna' },
  { key: 'dkk', value: 'DKK', name: 'Danish Krone' },
  { key: 'dzd', value: 'DZD', name: 'Algerian Dinar' },
  { key: 'egp', value: 'EGP', name: 'Egyptian Pound' },
  { key: 'etb', value: 'ETB', name: 'Ethiopian Birr' },
  { key: 'gel', value: 'GEL', name: 'Georgian Lari' },
  { key: 'ghs', value: 'GHS', name: 'Ghanaian Cedi' },
  { key: 'gip', value: 'GIP', name: 'Gibraltar Pound' },
  { key: 'hkd', value: 'HKD', name: 'Hong Kong Dollar' },
  { key: 'hrk', value: 'HRK', name: 'Croatian Kuna' },
  { key: 'huf', value: 'HUF', name: 'Hungarian Forint' },
  { key: 'idr', value: 'IDR', name: 'Indonesian Rupiah' },
  { key: 'ils', value: 'ILS', name: 'Israeli New Sheqel' },
  { key: 'isk', value: 'ISK', name: 'Icelandic Króna' },
  { key: 'jmd', value: 'JMD', name: 'Jamaican Dollar' },
  { key: 'kes', value: 'KES', name: 'Kenyan Shilling' },
  { key: 'lkr', value: 'LKR', name: 'Sri Lankan Rupee' },
  { key: 'mad', value: 'MAD', name: 'Moroccan Dirham' },
  { key: 'mur', value: 'MUR', name: 'Mauritian Rupee' },
  { key: 'mvr', value: 'MVR', name: 'Maldivian Rufiyaa' },
  { key: 'mxn', value: 'MXN', name: 'Mexican Peso' },
  { key: 'myr', value: 'MYR', name: 'Malaysian Ringgit' },
  { key: 'ngn', value: 'NGN', name: 'Nigerian Naira' },
  { key: 'nok', value: 'NOK', name: 'Norwegian Krone' },
  { key: 'php', value: 'PHP', name: 'Philippine Peso' },
  { key: 'pln', value: 'PLN', name: 'Polish Zloty' },
  { key: 'qar', value: 'QAR', name: 'Qatari Rial' },
  { key: 'rwf', value: 'RWF', name: 'Rwandan Franc' },
  { key: 'sar', value: 'SAR', name: 'Saudi Riyal' },
  { key: 'sek', value: 'SEK', name: 'Swedish Krona' },
  { key: 'sgd', value: 'SGD', name: 'Singapore Dollar' },
  { key: 'try', value: 'TRY', name: 'Turkish Lira' }
];
